// Generated by scripts/export-deployment.ts. Do not edit by hand.
//
// Deployment record for the Madame Kimchi batch provenance registry.
// Every value here is public on-chain data. No secret is ever written here.

export const kimchiProvenanceDeployment = {
  /** Monad Testnet. */
  chainId: 10143,
  /** Deployed contract address. */
  address: "0xCBC03079CcdA3ef1E8700D0c0D66384c9918524F",
  /** Transaction that created the contract. */
  deploymentTxHash: "0xbaf61bf9370659869f08d8f88d395f47bbf6f657821cc85dd6b6c9fbaf37672e",
  /** Block the deployment landed in; a sensible `fromBlock` for log queries. */
  blockNumber: 48037641,
  /** Address seated as admin, verifier, and pauser by the constructor. */
  deployer: "0xda6e4b383eaf8290748392c21c46fa036a3064be",
  /** Ignition deployment this record came from. */
  deploymentId: "chain-10143",
} as const;
