/**
 * Exports the compiled KimchiProvenance ABI for the frontend.
 *
 *     node scripts/export-abi.ts
 *
 * Deliberately independent of deployment. An ABI is a property of the compiled
 * contract, not of any particular address, so the interface can be built and
 * type-checked against it before anything is deployed. The deployed *address*
 * is a separate concern and lives in `scripts/export-deployment.ts`.
 *
 * Opens no network connection and reads no account configuration.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ARTIFACT = join(ROOT, "artifacts/contracts/KimchiProvenance.sol/KimchiProvenance.json");
const OUT = join(ROOT, "src/lib/abi/kimchiProvenance.ts");

let abi: unknown;
try {
  abi = (JSON.parse(readFileSync(ARTIFACT, "utf8")) as { abi: unknown }).abi;
} catch {
  console.error(`\n  ✗ No compiled artifact at ${ARTIFACT}.\n    Run \`npx hardhat build\` first.\n`);
  process.exit(1);
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `// Generated by scripts/export-abi.ts. Do not edit by hand.
//
// ABI of the compiled KimchiProvenance contract. Public data.
//
// \`as const\` is required — viem and wagmi derive argument and return types
// from the literal ABI, and widening it to \`any[]\` erases all of that.

export const kimchiProvenanceAbi = ${JSON.stringify(abi, null, 2)} as const;
`,
  "utf8",
);

console.log(`  ✓ Exported ABI to src/lib/abi/kimchiProvenance.ts`);
